[package]
name = "ty-scip"
version = "0.1.0"
description = "A fast SCIP indexer for Python, powered by ty"
authors = ["Brendan Murphy"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/brendan-m-murphy/ty-scip"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
ruff_db = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd", default-features = false, features = ["os"] }
ruff_python_ast = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd" }
ruff_source_file = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd" }
ruff_text_size = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd" }
protobuf = "=3.7.2"
scip = "=0.10.0"
toml = "=1.1.5"
ty_ide = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd" }
ty_module_resolver = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd" }
ty_python_core = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd" }
ty_python_semantic = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd" }
ty_project = { git = "https://github.com/astral-sh/ruff", rev = "12132db2885084f4b87aafc5908e336e7b5e8fbd", default-features = false }
url = "=2.5.8"
