[build-system]
requires = ["maturin==1.15.0"]
build-backend = "maturin"

[project]
name = "ty-scip"
dynamic = ["version"]
description = "A fast SCIP indexer for Python, powered by ty"
readme = "README.md"
authors = [{ name = "Brendan Murphy" }]
license = "MIT"
license-files = ["LICENSE", "THIRD_PARTY_NOTICES"]

[project.urls]
Repository = "https://github.com/brendan-m-murphy/ty-scip"
Issues = "https://github.com/brendan-m-murphy/ty-scip/issues"

[tool.maturin]
bindings = "bin"
strip = true

[tool.maturin.sbom]
rust = false
auditwheel = false
